### ISSUE TITLE
Unable to properly use Dexter

### ISSUE THREAD

**Issue by NickJorens** [IndigoProtocol/dexter#58]
### Data Provider

Blockfrost

### DEX

All

### Description

I'm having issues with how Dexter is set up.
I created a minimal reproduction of this error in a separate repository.

https://github.com/NickJorens/dexter

`npx tsc`
`node build/src/index.js`

Any help or insights are greatly appreciated.

**Comment by Sluder** [comment]
@NickJorens Im assuming your issue here is running a project with Dexter, could you try running the project with the `--es-module-specifier-resolution=node` flag? So `node --es-module-specifier-resolution=node build/src/index.js`

**Comment by NickJorens** [comment]
@Sluder I'm still getting an error. I also defined that in my [tsconfig.json](https://github.com/NickJorens/dexter/blob/main/tsconfig.json)

```
➜  dexter git:(main) node --es-module-specifier-resolution=node build/src/index.js
node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module '/Users/nick/dexter/build/src/index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.4.0
```

**Comment by Sluder** [comment]
@NickJorens I pulled your project & got it running by adding `"skipLibCheck": true` in the tsconfig, could you try that out?

**Comment by NickJorens** [comment]
@Sluder I'm sorry but that didn't resolve the error. What version of Node are you running?

```➜  dexter git:(main) ✗ node --es-module-specifier-resolution=node build/src/index.js
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/nick/dexter/node_modules/@indigo-labs/dexter/build/constants' imported from /Users/nick/dexter/node_modules/@indigo-labs/dexter/build/index.js
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:225:11)
    at moduleResolve (node:internal/modules/esm/resolve:837:10)
    at defaultResolve (node:internal/modules/esm/resolve:1035:11)
    at DefaultModuleLoader.resolve (node:internal/modules/esm/loader:251:12)
    at DefaultModuleLoader.getModuleJob (node:internal/modules/esm/loader:140:32)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:33)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v20.4.0```

I updated the repo with your change.

**Comment by Sluder** [comment]
Sorry forgot to add, I got it running by adding the skipLibCheck & using the `--es-module-specifier-resolution=node` flag when running the project. I am on node version v18.16

**Comment by NickJorens** [comment]
@Sluder So it seems this package is incompatible with v20.x
Works fine on v18.16 LTS

I'll switch to LTS for now. 
Something to be aware of in the future :)

Thanks for your help!

**Comment by Sluder** [comment]
Interesting find, appreciate you letting me know!
We've had this issue open to investigate the requirements as well https://github.com/IndigoProtocol/dexter/issues/28
